require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DiagnosesController do

  def mock_diagnosis(stubs={})
    @mock_diagnosis ||= mock_model(Diagnosis, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all diagnoses as @diagnoses" do
      Diagnosis.stub(:all) { [mock_diagnosis] }
      get :index
      assigns(:diagnoses).should eq([mock_diagnosis])
    end
  end

  describe "GET show" do
    it "assigns the requested diagnosis as @diagnosis" do
      Diagnosis.stub(:find).with("37") { mock_diagnosis }
      get :show, :id => "37"
      assigns(:diagnosis).should be(mock_diagnosis)
    end
  end

  describe "GET new" do
    it "assigns a new diagnosis as @diagnosis" do
      Diagnosis.stub(:new) { mock_diagnosis }
      get :new
      assigns(:diagnosis).should be(mock_diagnosis)
    end
  end

  describe "GET edit" do
    it "assigns the requested diagnosis as @diagnosis" do
      Diagnosis.stub(:find).with("37") { mock_diagnosis }
      get :edit, :id => "37"
      assigns(:diagnosis).should be(mock_diagnosis)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created diagnosis as @diagnosis" do
        Diagnosis.stub(:new).with({'these' => 'params'}) { mock_diagnosis(:save => true) }
        post :create, :diagnosis => {'these' => 'params'}
        assigns(:diagnosis).should be(mock_diagnosis)
      end

      it "redirects to the created diagnosis" do
        Diagnosis.stub(:new) { mock_diagnosis(:save => true) }
        post :create, :diagnosis => {}
        response.should redirect_to(diagnosis_url(mock_diagnosis))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved diagnosis as @diagnosis" do
        Diagnosis.stub(:new).with({'these' => 'params'}) { mock_diagnosis(:save => false) }
        post :create, :diagnosis => {'these' => 'params'}
        assigns(:diagnosis).should be(mock_diagnosis)
      end

      it "re-renders the 'new' template" do
        Diagnosis.stub(:new) { mock_diagnosis(:save => false) }
        post :create, :diagnosis => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested diagnosis" do
        Diagnosis.stub(:find).with("37") { mock_diagnosis }
        mock_diagnosis.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :diagnosis => {'these' => 'params'}
      end

      it "assigns the requested diagnosis as @diagnosis" do
        Diagnosis.stub(:find) { mock_diagnosis(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:diagnosis).should be(mock_diagnosis)
      end

      it "redirects to the diagnosis" do
        Diagnosis.stub(:find) { mock_diagnosis(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(diagnosis_url(mock_diagnosis))
      end
    end

    describe "with invalid params" do
      it "assigns the diagnosis as @diagnosis" do
        Diagnosis.stub(:find) { mock_diagnosis(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:diagnosis).should be(mock_diagnosis)
      end

      it "re-renders the 'edit' template" do
        Diagnosis.stub(:find) { mock_diagnosis(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested diagnosis" do
      Diagnosis.stub(:find).with("37") { mock_diagnosis }
      mock_diagnosis.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the diagnoses list" do
      Diagnosis.stub(:find) { mock_diagnosis }
      delete :destroy, :id => "1"
      response.should redirect_to(diagnoses_url)
    end
  end

end
