require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FunctionalScenariosController do

  def mock_functional_scenario(stubs={})
    @mock_functional_scenario ||= mock_model(FunctionalScenario, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all functional_scenarios as @functional_scenarios" do
      FunctionalScenario.stub(:all) { [mock_functional_scenario] }
      get :index
      assigns(:functional_scenarios).should eq([mock_functional_scenario])
    end
  end

  describe "GET show" do
    it "assigns the requested functional_scenario as @functional_scenario" do
      FunctionalScenario.stub(:find).with("37") { mock_functional_scenario }
      get :show, :id => "37"
      assigns(:functional_scenario).should be(mock_functional_scenario)
    end
  end

  describe "GET new" do
    it "assigns a new functional_scenario as @functional_scenario" do
      FunctionalScenario.stub(:new) { mock_functional_scenario }
      get :new
      assigns(:functional_scenario).should be(mock_functional_scenario)
    end
  end

  describe "GET edit" do
    it "assigns the requested functional_scenario as @functional_scenario" do
      FunctionalScenario.stub(:find).with("37") { mock_functional_scenario }
      get :edit, :id => "37"
      assigns(:functional_scenario).should be(mock_functional_scenario)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created functional_scenario as @functional_scenario" do
        FunctionalScenario.stub(:new).with({'these' => 'params'}) { mock_functional_scenario(:save => true) }
        post :create, :functional_scenario => {'these' => 'params'}
        assigns(:functional_scenario).should be(mock_functional_scenario)
      end

      it "redirects to the created functional_scenario" do
        FunctionalScenario.stub(:new) { mock_functional_scenario(:save => true) }
        post :create, :functional_scenario => {}
        response.should redirect_to(functional_scenario_url(mock_functional_scenario))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved functional_scenario as @functional_scenario" do
        FunctionalScenario.stub(:new).with({'these' => 'params'}) { mock_functional_scenario(:save => false) }
        post :create, :functional_scenario => {'these' => 'params'}
        assigns(:functional_scenario).should be(mock_functional_scenario)
      end

      it "re-renders the 'new' template" do
        FunctionalScenario.stub(:new) { mock_functional_scenario(:save => false) }
        post :create, :functional_scenario => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested functional_scenario" do
        FunctionalScenario.stub(:find).with("37") { mock_functional_scenario }
        mock_functional_scenario.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :functional_scenario => {'these' => 'params'}
      end

      it "assigns the requested functional_scenario as @functional_scenario" do
        FunctionalScenario.stub(:find) { mock_functional_scenario(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:functional_scenario).should be(mock_functional_scenario)
      end

      it "redirects to the functional_scenario" do
        FunctionalScenario.stub(:find) { mock_functional_scenario(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(functional_scenario_url(mock_functional_scenario))
      end
    end

    describe "with invalid params" do
      it "assigns the functional_scenario as @functional_scenario" do
        FunctionalScenario.stub(:find) { mock_functional_scenario(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:functional_scenario).should be(mock_functional_scenario)
      end

      it "re-renders the 'edit' template" do
        FunctionalScenario.stub(:find) { mock_functional_scenario(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested functional_scenario" do
      FunctionalScenario.stub(:find).with("37") { mock_functional_scenario }
      mock_functional_scenario.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the functional_scenarios list" do
      FunctionalScenario.stub(:find) { mock_functional_scenario }
      delete :destroy, :id => "1"
      response.should redirect_to(functional_scenarios_url)
    end
  end

end
