require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ScannerHardwaresController do

  def mock_scanner_hardware(stubs={})
    @mock_scanner_hardware ||= mock_model(ScannerHardware, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all scanner_hardwares as @scanner_hardwares" do
      ScannerHardware.stub(:all) { [mock_scanner_hardware] }
      get :index
      assigns(:scanner_hardwares).should eq([mock_scanner_hardware])
    end
  end

  describe "GET show" do
    it "assigns the requested scanner_hardware as @scanner_hardware" do
      ScannerHardware.stub(:find).with("37") { mock_scanner_hardware }
      get :show, :id => "37"
      assigns(:scanner_hardware).should be(mock_scanner_hardware)
    end
  end

  describe "GET new" do
    it "assigns a new scanner_hardware as @scanner_hardware" do
      ScannerHardware.stub(:new) { mock_scanner_hardware }
      get :new
      assigns(:scanner_hardware).should be(mock_scanner_hardware)
    end
  end

  describe "GET edit" do
    it "assigns the requested scanner_hardware as @scanner_hardware" do
      ScannerHardware.stub(:find).with("37") { mock_scanner_hardware }
      get :edit, :id => "37"
      assigns(:scanner_hardware).should be(mock_scanner_hardware)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created scanner_hardware as @scanner_hardware" do
        ScannerHardware.stub(:new).with({'these' => 'params'}) { mock_scanner_hardware(:save => true) }
        post :create, :scanner_hardware => {'these' => 'params'}
        assigns(:scanner_hardware).should be(mock_scanner_hardware)
      end

      it "redirects to the created scanner_hardware" do
        ScannerHardware.stub(:new) { mock_scanner_hardware(:save => true) }
        post :create, :scanner_hardware => {}
        response.should redirect_to(scanner_hardware_url(mock_scanner_hardware))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scanner_hardware as @scanner_hardware" do
        ScannerHardware.stub(:new).with({'these' => 'params'}) { mock_scanner_hardware(:save => false) }
        post :create, :scanner_hardware => {'these' => 'params'}
        assigns(:scanner_hardware).should be(mock_scanner_hardware)
      end

      it "re-renders the 'new' template" do
        ScannerHardware.stub(:new) { mock_scanner_hardware(:save => false) }
        post :create, :scanner_hardware => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scanner_hardware" do
        ScannerHardware.stub(:find).with("37") { mock_scanner_hardware }
        mock_scanner_hardware.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :scanner_hardware => {'these' => 'params'}
      end

      it "assigns the requested scanner_hardware as @scanner_hardware" do
        ScannerHardware.stub(:find) { mock_scanner_hardware(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:scanner_hardware).should be(mock_scanner_hardware)
      end

      it "redirects to the scanner_hardware" do
        ScannerHardware.stub(:find) { mock_scanner_hardware(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(scanner_hardware_url(mock_scanner_hardware))
      end
    end

    describe "with invalid params" do
      it "assigns the scanner_hardware as @scanner_hardware" do
        ScannerHardware.stub(:find) { mock_scanner_hardware(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:scanner_hardware).should be(mock_scanner_hardware)
      end

      it "re-renders the 'edit' template" do
        ScannerHardware.stub(:find) { mock_scanner_hardware(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scanner_hardware" do
      ScannerHardware.stub(:find).with("37") { mock_scanner_hardware }
      mock_scanner_hardware.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the scanner_hardwares list" do
      ScannerHardware.stub(:find) { mock_scanner_hardware }
      delete :destroy, :id => "1"
      response.should redirect_to(scanner_hardwares_url)
    end
  end

end
