require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SeriesSetsController do

  def mock_series_set(stubs={})
    @mock_series_set ||= mock_model(SeriesSet, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all series_sets as @series_sets" do
      SeriesSet.stub(:all) { [mock_series_set] }
      get :index
      assigns(:series_sets).should eq([mock_series_set])
    end
  end

  describe "GET show" do
    it "assigns the requested series_set as @series_set" do
      SeriesSet.stub(:find).with("37") { mock_series_set }
      get :show, :id => "37"
      assigns(:series_set).should be(mock_series_set)
    end
  end

  describe "GET new" do
    it "assigns a new series_set as @series_set" do
      SeriesSet.stub(:new) { mock_series_set }
      get :new
      assigns(:series_set).should be(mock_series_set)
    end
  end

  describe "GET edit" do
    it "assigns the requested series_set as @series_set" do
      SeriesSet.stub(:find).with("37") { mock_series_set }
      get :edit, :id => "37"
      assigns(:series_set).should be(mock_series_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created series_set as @series_set" do
        SeriesSet.stub(:new).with({'these' => 'params'}) { mock_series_set(:save => true) }
        post :create, :series_set => {'these' => 'params'}
        assigns(:series_set).should be(mock_series_set)
      end

      it "redirects to the created series_set" do
        SeriesSet.stub(:new) { mock_series_set(:save => true) }
        post :create, :series_set => {}
        response.should redirect_to(series_set_url(mock_series_set))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved series_set as @series_set" do
        SeriesSet.stub(:new).with({'these' => 'params'}) { mock_series_set(:save => false) }
        post :create, :series_set => {'these' => 'params'}
        assigns(:series_set).should be(mock_series_set)
      end

      it "re-renders the 'new' template" do
        SeriesSet.stub(:new) { mock_series_set(:save => false) }
        post :create, :series_set => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested series_set" do
        SeriesSet.stub(:find).with("37") { mock_series_set }
        mock_series_set.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :series_set => {'these' => 'params'}
      end

      it "assigns the requested series_set as @series_set" do
        SeriesSet.stub(:find) { mock_series_set(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:series_set).should be(mock_series_set)
      end

      it "redirects to the series_set" do
        SeriesSet.stub(:find) { mock_series_set(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(series_set_url(mock_series_set))
      end
    end

    describe "with invalid params" do
      it "assigns the series_set as @series_set" do
        SeriesSet.stub(:find) { mock_series_set(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:series_set).should be(mock_series_set)
      end

      it "re-renders the 'edit' template" do
        SeriesSet.stub(:find) { mock_series_set(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested series_set" do
      SeriesSet.stub(:find).with("37") { mock_series_set }
      mock_series_set.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the series_sets list" do
      SeriesSet.stub(:find) { mock_series_set }
      delete :destroy, :id => "1"
      response.should redirect_to(series_sets_url)
    end
  end

end
