require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SeriesScenariosController do

  def mock_series_scenario(stubs={})
    @mock_series_scenario ||= mock_model(SeriesScenario, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all series_scenarios as @series_scenarios" do
      SeriesScenario.stub(:all) { [mock_series_scenario] }
      get :index
      assigns(:series_scenarios).should eq([mock_series_scenario])
    end
  end

  describe "GET show" do
    it "assigns the requested series_scenario as @series_scenario" do
      SeriesScenario.stub(:find).with("37") { mock_series_scenario }
      get :show, :id => "37"
      assigns(:series_scenario).should be(mock_series_scenario)
    end
  end

  describe "GET new" do
    it "assigns a new series_scenario as @series_scenario" do
      SeriesScenario.stub(:new) { mock_series_scenario }
      get :new
      assigns(:series_scenario).should be(mock_series_scenario)
    end
  end

  describe "GET edit" do
    it "assigns the requested series_scenario as @series_scenario" do
      SeriesScenario.stub(:find).with("37") { mock_series_scenario }
      get :edit, :id => "37"
      assigns(:series_scenario).should be(mock_series_scenario)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created series_scenario as @series_scenario" do
        SeriesScenario.stub(:new).with({'these' => 'params'}) { mock_series_scenario(:save => true) }
        post :create, :series_scenario => {'these' => 'params'}
        assigns(:series_scenario).should be(mock_series_scenario)
      end

      it "redirects to the created series_scenario" do
        SeriesScenario.stub(:new) { mock_series_scenario(:save => true) }
        post :create, :series_scenario => {}
        response.should redirect_to(series_scenario_url(mock_series_scenario))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved series_scenario as @series_scenario" do
        SeriesScenario.stub(:new).with({'these' => 'params'}) { mock_series_scenario(:save => false) }
        post :create, :series_scenario => {'these' => 'params'}
        assigns(:series_scenario).should be(mock_series_scenario)
      end

      it "re-renders the 'new' template" do
        SeriesScenario.stub(:new) { mock_series_scenario(:save => false) }
        post :create, :series_scenario => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested series_scenario" do
        SeriesScenario.stub(:find).with("37") { mock_series_scenario }
        mock_series_scenario.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :series_scenario => {'these' => 'params'}
      end

      it "assigns the requested series_scenario as @series_scenario" do
        SeriesScenario.stub(:find) { mock_series_scenario(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:series_scenario).should be(mock_series_scenario)
      end

      it "redirects to the series_scenario" do
        SeriesScenario.stub(:find) { mock_series_scenario(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(series_scenario_url(mock_series_scenario))
      end
    end

    describe "with invalid params" do
      it "assigns the series_scenario as @series_scenario" do
        SeriesScenario.stub(:find) { mock_series_scenario(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:series_scenario).should be(mock_series_scenario)
      end

      it "re-renders the 'edit' template" do
        SeriesScenario.stub(:find) { mock_series_scenario(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested series_scenario" do
      SeriesScenario.stub(:find).with("37") { mock_series_scenario }
      mock_series_scenario.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the series_scenarios list" do
      SeriesScenario.stub(:find) { mock_series_scenario }
      delete :destroy, :id => "1"
      response.should redirect_to(series_scenarios_url)
    end
  end

end
